<a href="https://colab.research.google.com/github/divyaa-vermaa03/Practice_codes/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
d_array = np.array([1, 2, 3, 4, 5, 2.5, 6.8, 4.7, 3.2])
print(d_array)

[1.  2.  3.  4.  5.  2.5 6.8 4.7 3.2]


In [13]:
twod_array = np.array([[1,2], [3,4], [2.4, 8.3]])
print(twod_array)

[[1.  2. ]
 [3.  4. ]
 [2.4 8.3]]


In [17]:
zero_array = np.zeros(6)
print(zero_array)

[0. 0. 0. 0. 0. 0.]


In [19]:
zero_array = np.zeros((6,5))
print(zero_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
zero_array = np.zeros((6,3), dtype= int)
print(zero_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [21]:
sequence_of_integers = np.arange(5, 21)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [23]:
random_integer_between50and100 = np.random.randint(low=50, high=101, size=(6))
print(random_integer_between50and100)

[ 55  56  88  98  88 100]


In [27]:
random_floats_between_0_and_1 = np.random.random(size=(6))
print(random_floats_between_0_and_1)

[0.54848328 0.24023419 0.45152746 0.23780763 0.09173998 0.75896406]
